### ISSUE TITLE
observer

### ISSUE THREAD

**Issue by SzymanskiBlazej** [opereon/opereon-website#1]
Error:
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'disconnect' of null (OnThisPage.vue:65)

**Comment by AnnaKaminska** [comment]
Zmiany zostały cofnięte, ponieważ sypało błędami na konsoli aż miło i widok nie działał.
Proszę o ponowne przeanalizowanie problemu

**Comment by AnnaKaminska** [comment]
Naprawione
